# Generated by Django 4.2.6 on 2023-11-09 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseprofile',
            name='image',
            field=models.ImageField(default='default.jpg', max_length=255, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='baseprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='enter valid mobile number', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
