# Generated by Django 4.2.6 on 2023-10-21 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subrole',
            name='main_role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subroles', to='users.role'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='sub_roles',
            field=models.ManyToManyField(blank=True, to='users.subrole'),
        ),
    ]
