# Generated by Django 5.0.4 on 2024-05-04 16:06

from django.db import migrations

def initialize_roles(apps, schema_editor):
    Role = apps.get_model('users', 'Role')  # Replace 'yourappname' with your actual app name

    # Define predefined roles
    default_roles = [
        'ADMIN',
        'USER',
        'STAFF',
    ]

    for role in default_roles:
        Role.objects.get_or_create(name=role)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initialize_roles),
    ]
