# Generated by Django 4.2.6 on 2023-10-21 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subrole_main_role_alter_role_sub_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='sub_roles',
            field=models.ManyToManyField(default=None, to='users.subrole'),
        ),
        migrations.AlterField(
            model_name='subrole',
            name='main_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subroles', to='users.role'),
        ),
    ]
