# Generated by Django 4.2.6 on 2023-10-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20231021_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User'), ('STAFF', 'Staff')], editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
