# Generated by Django 4.2.6 on 2023-10-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='sub_roles',
            field=models.ManyToManyField(null=True, to='users.subrole'),
        ),
    ]
