# Generated by Django 4.2.6 on 2023-10-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_role_sub_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='sub_roles',
            field=models.ManyToManyField(default=None, to='users.subrole'),
        ),
    ]
