# Generated by Django 4.2.6 on 2023-10-22 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_role_sub_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subrole',
            name='main_role',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subroles', to='users.role'),
        ),
    ]
