# Generated by Django 4.2.6 on 2023-10-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_role_sub_roles_alter_subrole_main_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sub_role',
            field=models.ManyToManyField(to='users.subrole'),
        ),
    ]
