# Generated by Django 4.2.6 on 2023-10-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_sub_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='sub_role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='sub_roles',
            field=models.ManyToManyField(default=None, to='users.subrole'),
        ),
    ]
