# Generated by Django 4.2.6 on 2023-10-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_customuser_sub_role_customuser_sub_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sub_roles',
            field=models.ManyToManyField(to='users.subrole'),
        ),
    ]
