# Generated by Django 4.2.6 on 2023-10-24 05:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_sub_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, max_length=250, null=True)),
                ('pincode', models.IntegerField(blank=True, max_length=10, null=True)),
                ('mobile_number', models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='enter valid mobile number', regex='^\\+?1?\\d{9,15}$')])),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('baseprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='users.baseprofile')),
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mobile_verified', models.BooleanField(default=False)),
            ],
            bases=('users.baseprofile',),
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('baseprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='users.baseprofile')),
                ('staff_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('qualifications', models.TextField(blank=True, max_length=200, null=True)),
            ],
            bases=('users.baseprofile',),
        ),
    ]
