# Generated by Django 4.2.6 on 2023-10-24 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_baseprofile_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='baseprofile_ptr',
        ),
        migrations.DeleteModel(
            name='ClientProfile',
        ),
        migrations.DeleteModel(
            name='StaffProfile',
        ),
    ]
