# Generated by Django 4.2.6 on 2023-10-24 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_staffprofile_baseprofile_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
    ]
