# Generated by Django 4.2.6 on 2023-10-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sub_roles',
            field=models.ManyToManyField(default=None, to='users.subrole'),
        ),
    ]
