# Generated by Django 4.2.6 on 2023-10-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_customuser_sub_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sub_roles',
            field=models.ManyToManyField(blank=True, default=None, to='users.subrole'),
        ),
    ]
