# Generated by Django 4.2.6 on 2023-10-31 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_customuser_sub_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseprofile',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
