# Generated by Django 4.2.6 on 2023-10-21 17:41

from django.db import migrations
from users.models import Role, SubRole


def populate_subrole(apps, schema_editor):
    # SubRole = apps.get_model('users', 'SubRole')
    
    initial_subroles = ['Manager', 'Cashier', 'Receptionist']
    for role in initial_subroles:
        SubRole.objects.get_or_create(name=role)

def populate_role(apps, schema_editor):
    # Role = apps.get_model('users', 'Role')

    for role_code, role_name in Role.USER_TYPES:
        Role.objects.get_or_create(name=role_code)
        
        
class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_role_sub_roles_alter_subrole_main_role'),
    ]

    operations = [
        migrations.RunPython(populate_subrole),
        migrations.RunPython(populate_role),
    ]
