# Generated by Django 5.0.4 on 2024-05-04 16:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('baseprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.baseprofile')),
                ('staff_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=25)),
                ('qualifications', models.TextField(blank=True, max_length=200, null=True)),
            ],
            bases=('users.baseprofile',),
        ),
    ]
