# Generated by Django 4.2.6 on 2023-11-06 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=10, null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tokenapp.status')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_date', models.DateField(default=django.utils.timezone.now)),
                ('token_time', models.TimeField(default=django.utils.timezone.now)),
                ('custom_service', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('token_modified', models.DateTimeField(auto_now_add=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens_assigned_to_staff', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens_for_service', to='tokenapp.service')),
                ('status', models.ForeignKey(default='Pending', on_delete=django.db.models.deletion.PROTECT, related_name='tokens_with_status', to='tokenapp.status')),
                ('status_history', models.ManyToManyField(related_name='tokens_in_status_history', through='tokenapp.StatusHistory', to='tokenapp.status')),
                ('status_was', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tokens_with_status_was', to='tokenapp.status')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens_created_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='statushistory',
            name='tracked_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokenapp.token'),
        ),
    ]
