# Generated by Django 4.2.6 on 2023-11-06 04:13

from django.db import migrations
from tokenapp.models import Status, Service

def populate_status(apps, schema_editor):
    initial_statuses = ['Booked', 'Pending', 'Paid', 'Completed', 'Rejected', 'Payment Pending']
    for status in initial_statuses:
        Status.objects.get_or_create(name=status)
        
def other_service(apps, schema_editor):
    if not Service.objects.filter(name='Other', code='OTH').exists():
        Service.objects.create(name='Other', code='OTH', is_default=True)


class Migration(migrations.Migration):

    dependencies = [
        ('tokenapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_status),
        migrations.RunPython(other_service)
    ]
