# Generated by Django 5.0.4 on 2024-05-04 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tokenapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens_assigned_to_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='token',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens_for_service', to='tokenapp.service'),
        ),
        migrations.AddField(
            model_name='token',
            name='status',
            field=models.ForeignKey(default='Pending', on_delete=django.db.models.deletion.PROTECT, related_name='tokens_with_status', to='tokenapp.status'),
        ),
        migrations.AddField(
            model_name='token',
            name='status_history',
            field=models.ManyToManyField(related_name='tokens_in_status_history', through='tokenapp.StatusHistory', to='tokenapp.status'),
        ),
        migrations.AddField(
            model_name='token',
            name='status_was',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tokens_with_status_was', to='tokenapp.status'),
        ),
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens_created_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='tracked_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokenapp.token'),
        ),
    ]
