# Generated by Django 5.0.4 on 2024-05-04 16:36

from django.db import migrations

def initialize_token_status(apps, schema_editor):
    Status = apps.get_model('tokenapp', 'Status')
    
    default_status = [
        'Booked',
        'Pending',
        'Rejected',
        'Cancelled',
        'Completed',
        'Paid',
    ]

    for status in default_status:
        Status.objects.get_or_create(name=status)

class Migration(migrations.Migration):

    dependencies = [
        ('tokenapp', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(initialize_token_status)
    ]
