# Generated by Django 4.2.6 on 2023-11-02 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokenapp', '0004_token_assigned_staff_token_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='status',
            field=models.ForeignKey(default='Pending', on_delete=django.db.models.deletion.PROTECT, related_name='tokens_with_status', to='tokenapp.status'),
        ),
    ]
