# Generated by Django 4.2.6 on 2023-11-02 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tokenapp', '0005_alter_token_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens_assigned_to_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
