# Generated by Django 4.2.6 on 2023-11-02 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokenapp', '0006_alter_token_assigned_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='status_was',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tokens_with_status_was', to='tokenapp.status'),
        ),
    ]
