# Generated by Django 4.2.6 on 2023-11-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokenapp', '0007_token_status_was'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='status_history',
        ),
    ]
