# Generated by Django 4.2.6 on 2023-11-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenapp', '0008_remove_token_status_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='status_history',
            field=models.ManyToManyField(related_name='tokens_in_status_history', through='tokenapp.StatusHistory', to='tokenapp.status'),
        ),
    ]
