# Generated by Django 4.2.6 on 2023-10-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purpose',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
