# Generated by Django 4.2.6 on 2023-10-25 12:43

from django.db import migrations


def other_purpose(apps, schema_editor):
    Purpose = apps.get_model('slot', 'Purpose')
    if not Purpose.objects.filter(name='Other', code='OTH').exists():
        Purpose.objects.create(name='Other', code='OTH', is_default=True)

class Migration(migrations.Migration):
    
    dependencies = [
        ('slot', '0002_purpose_is_default'),
    ]

    operations = [
        migrations.RunPython(other_purpose)
    ]
